<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vtt-cntt-l-77-HP-ProDesk-400-G5-MT-IDS-APJ" name="org.selenium.automationtest.testsuite.TS_QLBH_BanhangNoibo" tests="1" failures="1" timestamp="19 Aug 2019 06:57:22 GMT" time="33.899" errors="0">
  <testcase name="TC_001_BanHangNB_KhongCTBH_DienThoai" time="33.899" classname="org.selenium.automationtest.testsuite.TS_QLBH_BanhangNoibo">
    <failure type="java.lang.AssertionError" message="So sanh khong bang nhau: 3 va 2 expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: So sanh khong bang nhau: 3 va 2 expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.selenium.automationtest.common.CommonBase.verifyCompare(CommonBase.java:893)
	at org.selenium.automationtest.testsuite.TS_QLBH_BanhangNoibo.TC_001_BanHangNB_KhongCTBH_DienThoai(TS_QLBH_BanhangNoibo.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_001_BanHangNB_KhongCTBH_DienThoai -->
</testsuite> <!-- org.selenium.automationtest.testsuite.TS_QLBH_BanhangNoibo -->
